-- ============================================================
-- Final Year Project Tracking System (FYPTS)
-- Database: fypts
-- Version: 1.0
-- Description: SQL script to create database, tables, and
--              seed data for the FYPTS application.
-- ============================================================

CREATE DATABASE IF NOT EXISTS fypts
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE fypts;

-- ============================================================
-- TABLE: users
-- Stores all system users (Admin, Supervisor, Student)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('Admin', 'Supervisor', 'Student') NOT NULL DEFAULT 'Student',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- TABLE: projects
-- Stores final year project information
-- ============================================================
CREATE TABLE IF NOT EXISTS projects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_title VARCHAR(200) NOT NULL,
    student_name VARCHAR(100) NOT NULL,
    supervisor_name VARCHAR(100) NOT NULL,
    description TEXT,
    start_date DATE DEFAULT NULL,
    expected_completion DATE DEFAULT NULL,
    status ENUM(
        'Proposal Submitted',
        'Approved',
        'Design Phase',
        'Development Phase',
        'Testing Phase',
        'Completed'
    ) NOT NULL DEFAULT 'Proposal Submitted',
    progress_percentage INT DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- SEED DATA: Default Admin User
-- Password: admin123 (hashed with password_hash)
-- ============================================================
INSERT INTO users (fullname, email, password, role) VALUES
('System Admin', 'admin@fypts.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin'),
('Dr. Sarah Johnson', 'sarah.johnson@university.edu', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Supervisor'),
('Prof. Michael Chen', 'michael.chen@university.edu', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Supervisor'),
('John Doe', 'john.doe@student.edu', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Student'),
('Jane Smith', 'jane.smith@student.edu', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Student');

-- Note: The password hash above is for "password". For admin123, the hash
-- will be generated by the register script on first use. For demo purposes,
-- all seed users have password "password".

-- ============================================================
-- SEED DATA: Sample Projects
-- ============================================================
INSERT INTO projects (project_title, student_name, supervisor_name, description, start_date, expected_completion, status, progress_percentage) VALUES
('AI-Powered Chatbot for Student Admissions', 'John Doe', 'Dr. Sarah Johnson', 'An intelligent chatbot system that answers prospective student queries about admission requirements, deadlines, and campus facilities using natural language processing.', '2025-09-01', '2026-05-15', 'Development Phase', 60),
('Blockchain-Based Academic Certificate Verification', 'Jane Smith', 'Prof. Michael Chen', 'A decentralized system for issuing and verifying academic certificates using blockchain technology to prevent forgery.', '2025-09-15', '2026-06-01', 'Design Phase', 30),
('Smart Campus Navigation Mobile Application', 'Alice Wang', 'Dr. Sarah Johnson', 'A mobile application providing indoor and outdoor navigation for university campuses with real-time room availability and event notifications.', '2025-10-01', '2026-05-30', 'Proposal Submitted', 0),
('E-Learning Platform with Adaptive Learning Paths', 'Bob Brown', 'Prof. Michael Chen', 'An adaptive e-learning platform that personalizes learning paths based on student performance, learning style, and progress analytics.', '2025-08-15', '2026-04-30', 'Testing Phase', 85),
('Automated Timetable Generation System', 'Carol Davis', 'Dr. Sarah Johnson', 'A constraint-based system for automatically generating university timetables that optimizes room utilization and satisfies lecturer preferences.', '2025-09-01', '2026-05-15', 'Approved', 10);
